service: whats-on-api

provider:
  name: aws
  runtime: nodejs8.10
  stage: staging
  region: eu-west-2

functions:
  proxy:
    handler: index.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

plugins:
  - serverless-webpack
  - serverless-offline
